export interface ReportsByTest {
  testCode: string;
  count: number;
}

export interface DualCount {
  mglCount: number;
  pgxCount: number;
  total: number;
}

// Amended/Corrected: grouped by reason + type only
export interface AmendedReason {
  reason: string;
  reportUnlockType: string;
  count: number;
}

export interface AmendedCorrected {
  mgl: AmendedReason[];
  lims: AmendedReason[];
}

export interface DelayedReport {
  delayedDays: number;
  numberOfCases: number;
}

export interface Summary {
  reportsByTest: ReportsByTest[];
  autogeneratedMgl: number;
  autogeneratedPgx: number;
  manualMgl: number;
  manualPgx: number;
  reanalysis: number;
  failedQuality: number;
  cancelled: number;
  upgradedOrders: number;
  delayedReports: DelayedReport[];
}

export interface StaticItem {
  name: string;
}

export interface DateRange {
  startDate: string;
  endDate: string;
}
