import { Injectable } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Observable } from 'rxjs';
import {
  AmendedCorrected, DualCount, ReportsByTest,
  StaticItem, Summary
} from '../models/metrics.models';
import { environment } from '../../environments/environment';

@Injectable({ providedIn: 'root' })
export class MetricsService {
  private readonly base = environment.apiBase;

  constructor(private http: HttpClient) {}

  private params(start: string, end: string): HttpParams {
    return new HttpParams().set('startDate', start).set('endDate', end);
  }

  getSummary(start: string, end: string): Observable<Summary> {
    return this.http.get<Summary>(`${this.base}/metrics/summary`, { params: this.params(start, end) });
  }

  getReportsByTest(start: string, end: string): Observable<ReportsByTest[]> {
    return this.http.get<ReportsByTest[]>(`${this.base}/metrics/reports-by-test`, { params: this.params(start, end) });
  }

  getAutogenerated(start: string, end: string): Observable<DualCount> {
    return this.http.get<DualCount>(`${this.base}/metrics/autogenerated`, { params: this.params(start, end) });
  }

  getManual(start: string, end: string): Observable<DualCount> {
    return this.http.get<DualCount>(`${this.base}/metrics/manual`, { params: this.params(start, end) });
  }

  getAmendedCorrected(start: string, end: string): Observable<AmendedCorrected> {
    return this.http.get<AmendedCorrected>(`${this.base}/metrics/amended-corrected`, { params: this.params(start, end) });
  }

  getWhiteLabelCustomers(): Observable<StaticItem[]> {
    return this.http.get<StaticItem[]>(`${this.base}/static/white-label-customers`);
  }

  getDiscreteDataCustomers(): Observable<StaticItem[]> {
    return this.http.get<StaticItem[]>(`${this.base}/static/discrete-data-customers`);
  }

  getDataDeliveryCustomers(): Observable<StaticItem[]> {
    return this.http.get<StaticItem[]>(`${this.base}/static/data-delivery-customers`);
  }

  getSystems(): Observable<StaticItem[]> {
    return this.http.get<StaticItem[]>(`${this.base}/static/systems`);
  }

  getResultAccess(): Observable<StaticItem[]> {
    return this.http.get<StaticItem[]>(`${this.base}/static/result-access`);
  }
}
